#!/bin/sh

if [ -n "$1" ] ; then
  BRANCH_BASE="$1"
else
  # auto find the right main branch
  for branch in main master ; do
    if git show-ref --verify --quiet "refs/heads/$branch" ; then
      BRANCH_BASE="$branch"
      break
    fi
  done
fi

if [ -z "$BRANCH_BASE" ] ; then
  echo "No branch base has been found! Please provide one."
  exit 1
fi

echo "Using the branch base $BRANCH_BASE"

git rebase -i "$(git merge-base "$BRANCH_BASE" HEAD)"
#git rebase -i --onto $BRANCH_BASE...
