#!/bin/sh

echo "Finding gaia base directory..."
while test ! -r README.md -a `pwd` != "/" ; do
  cd ..
done

basepwd=`pwd`

if test `basename $basepwd` != "gaia" ; then
  echo "ERROR : please be inside your gaia directory"
  exit 1
fi

echo Found $basepwd

if test -n "$1" ; then 
  echo "Reseting and applying $1"
  read -p "are you sure ?" enter

  git reset --hard b2g
  if echo $1 | grep -q github ; then
    hub am -3 "$1"
  else
    wget -O - "$1" | git am -3
  fi
fi

echo Changed files:
git diff --stat b2g

echo
echo gjslint check
git diff --name-only b2g | xargs gjslint --nojsdoc

read -p "Press enter to view the jshint check" enter

echo
echo jshint check
git diff --name-only b2g | grep \.js$ | xargs jshint

read -p "Press enter to view the diff" enter

git diff -U1000 b2g | vim -

