#!/bin/sh

if test -n "$1" ; then
  case "$1" in
    *github*|*bugzilla*)
      ;;
    *)
      echo "Usage: review [ bugzilla patch url | github PR url ]"
      echo "  The argument is optional."
      exit
      ;;
  esac
fi

echo "Finding repository's base directory..."
while test ! -d .git -a `pwd` != "/" ; do
  cd ..
done

basepwd=`pwd`

echo Found $basepwd

if test -n "$1" ; then 
  echo "Reseting and applying $1"
  read -p "are you sure ?" enter

  git reset --hard moz

  case "$1" in
    *github*)
      hub am -3 "$1"
      ;;
    *bugzilla*)
      wget -O - "$1" | git am -3
      ;;
  esac
  if test $? -ne 0 ; then
    read -p "Press enter to revert git am operation, CTRl-C to abort" enter
    git am --abort
    exit 1
  fi
fi

echo Changed files:
git diff --stat moz

echo
echo eslint check
git diff --name-only moz | grep \.js$ | xargs ./node_modules/.bin/eslint

read -p "Press enter to view the diff" enter

git diff -U1000 moz | vim -

